version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/authapp
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
