name: CI for Auth App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Run backend tests (if you have any)
        working-directory: ./server
        run: echo "no tests yet"

      - name: Build frontend
        working-directory: ./client
        run: npm run build
